### ISSUE TITLE
Migration does not work

### ISSUE THREAD

**Issue by agilov** [v0lume/yii2-meta-tags#2]
migrate --migrationPath="@vendor/v0lume/yii2-meta-tags/migrations"
does not work. something wrong with namespace maybe.

**Comment by agilov** [comment]
it shows list of new migrations from folder. but cant apply it

Apply the above migration? (yes|no) [no]:y
**\* applying m150312_172156_meta_tags
PHP Fatal error:  Class 'm150312_172156_meta_tags' not found in /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/controllers/MigrateController.php on line 124
PHP Stack trace:
PHP   1. {main}() /media/sf_webdev1/ss/yii:0
PHP   2. yii\base\Application->run() /media/sf_webdev1/ss/yii:24
PHP   3. yii\console\Application->handleRequest() /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/Application.php:375
PHP   4. yii\console\Application->runAction() /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/Application.php:143
PHP   5. yii\base\Module->runAction() /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/Application.php:167
PHP   6. yii\console\Controller->runAction() /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/Module.php:454
PHP   7. yii\base\Controller->runAction() /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/Controller.php:108
PHP   8. yii\base\InlineAction->runWithParams() /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/Controller.php:154
PHP   9. call_user_func_array:{/media/sf_webdev1/ss/vendor/yiisoft/yii2/base/InlineAction.php:55}() /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/InlineAction.php:55
PHP  10. yii\console\controllers\BaseMigrateController->actionUp() /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/InlineAction.php:55
PHP  11. yii\console\controllers\BaseMigrateController->migrateUp() /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php:151
PHP  12. yii\console\controllers\MigrateController->createMigration() /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php:561
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'm150312_172156_meta_tags' not found'

in /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/controllers/MigrateController.php:124

Stack trace:
#0 /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(151): yii\console\controllers\BaseMigrateController->migrateUp()
#1 /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/InlineAction.php(55): yii\console\controllers\BaseMigrateController->actionUp()
#2 /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/InlineAction.php(55): ::call_user_func_array:{/media/sf_webdev1/ss/vendor/yiisoft/yii2/base/InlineAction.php:55}()
#3 /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams()
#4 /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/Controller.php(108): yii\base\Controller->runAction()
#5 /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction()
#6 /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction()
#7 /media/sf_webdev1/ss/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction()
#8 /media/sf_webdev1/ss/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest()
#9 /media/sf_webdev1/ss/yii(24): yii\base\Application->run()
#10 {main}
webdev@webdev:/media/sf_webdev1/ss$ php yii migrate
Yii Migration Tool (based on Yii v2.0.7)

**Comment by v0lume** [comment]
Fixed with commit 1a94edb
