### ISSUE TITLE
I got error when doing migration

### ISSUE THREAD

**Issue by SerikK** [v0lume/yii2-meta-tags#3]
I got such error when migrating:
Yii Migration Tool (based on Yii v2.

Total 1 new migration to be applied:
        m150312_172156_meta_tags    

Apply the above migration? (yes|no) 
**\* applying m150312_172156_meta_tag
PHP Fatal Error 'yii\base\ErrorExceptags' not found'                    

in C:\OpenServer\domains\project\ventroller.php:170                     

Stack trace:                        
#0 [internal function]: yii\base\Err
#1 {main}

**Comment by SerikK** [comment]
Oh, I think I found what is the problem. Migration should be created. 
I run the following command: 
yii migrate/up m150312_172156_meta_tags

**Comment by hello-omny** [comment]
Something went wrong.  Migration file exist, but...

``` bash
$ php yii migrate --migrationPath="@vendor/v0lume/yii2-meta-tags/migrations"
Yii Migration Tool (based on Yii v2.0.9)

Total 1 new migration to be applied:
        m150312_172156_meta_tags

Apply the above migration? (yes|no) [no]:yes
*** applying m150312_172156_meta_tags
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'm150312_172156_meta_tags' not found'

in /www/site.loc/vendor/yiisoft/yii2/console/controllers/MigrateController.php:170

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

**Comment by hello-omny** [comment]
> Something went wrong. Migration file exist, but...

Removing namespace in migration file had fix this issue.
